
#=========================================================#
#=================== Project settings ====================#
#=========================================================#

productName: Style  # 产品或项目名称
productVersion: V1.0  # 产品或项目版本
copyrightYear: 2018  # 产品或项目版权年份
companyName: Style  # 软件提供商公司或个人名称
adminPath: /a  #管理基础路径
frontPath: /f  #前端基础路径
page:
  pageSize: 20  # 分页默认大小

test:
  names: ${adminPath}

#=========================================================#
#=================== Database settings ===================#
#=========================================================#

target-datasource:
  datasource-name: master
  master:
    default: true
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.10:3306/style?useSSL=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
#  slave:
#    default: false
#    driver: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.1.11:3306/backend?useSSL=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
#    username: root
#    password: root


#=========================================================#
#================= Mybatis Plus settings =================#
#=========================================================#

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  mapper-scan-path: com.style.modules.*.dao
  typeAliasesPackage: com.style.modules.*.entity  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-super-type: com.style.common.entity.BaseEntity
  global-config:
    sql-parser-cache: false
  configuration:
    executor-type: reuse
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true



#=========================================================#
#=================== Web MVC settings ====================#
#=========================================================#

web:
  view:  # MVC 视图相关
    root: /views
    themeName: default  # 页面主题名称
  interceptor:  # MVC 拦截器
    log:  # 后台管理日志记录拦截器
      enabled: true
      addPathPatterns: >
        ${adminPath}/**
      excludePathPatterns: >
        ${adminPath}/index,
        ${adminPath}/login,
        ${adminPath}/desktop,
        ${adminPath}/sys/online/count,
        ${adminPath}/state/server/rtInfo,
        ${adminPath}/**/treeData,
        ${adminPath}/file/**,
        ${adminPath}/tags/*,
        ${adminPath}/msg/**
    mobile:  # 手机视图拦截器
      enabled: false
      addPathPatterns: >
        ${frontPath}/**
      excludePathPatterns: ~
  staticFile: .html,.css,.js,.map,.png,.jpg,.gif,.jpeg,.bmp,.ico,.swf,.psd,.htc,.crx,.xpi,.exe,.ipa,.apk,.otf,.eot,.svg,.ttf,.woff,.woff2
  staticFileExcludeUri: /druid/
  validator:  # 自定义正则表达式验证（主键、登录名）
    id: '[a-zA-Z0-9_\-/#\u4e00-\u9fa5]{0,64}'
    user.loginCode: '[a-zA-Z0-9_\u4e00-\u9fa5]{4,20}'



#=========================================================#
#=================== Security settings ===================#
#=========================================================#

shiro:
  form: # 表单登录相关设置
    loginUrl: ${adminPath}/login
    logoutUrl: ${adminPath}/logout
    successUrl: ${adminPath}/index
  cas: # 单点登录相关配置
    serverUrl: http://192.168.1.3:8080/cas
    clientUrl: http://192.168.1.3:8180/style
    loginUrl: ${shiro.casServerUrl}?service=${shiro.casClientUrl}${adminPath}/login-cas
    logoutUrl: ${shiro.casServerUrl}/logout?service=${shiro.loginUrl}
    successUrl: ${shiro.casClientUrl}${adminPath}/index
    secretKey: ~  # 如果启用/sso/{username}/{token}单点登录，请修改此安全key并与单点登录系统key一致。
    encryptKey: true  # 是否加密单点登录安全Key
  loginSubmit:  # 登录提交信息加密
    secretKey: thinkgem,jeesite,com  # 登录提交信息安全Key，加密用户名、密码、验证码，后再提交（key设置为3个，用逗号分隔）
  isAllowMultiAddrLogin: true   # 是否允许账号多地登录，如果设置为false，同一个设备类型的其它地点登录的相同账号被踢下线
  filterChainDefinitions: |  # URI 权限过滤器定义
    /ReportServer/** = user
    ${adminPath}/** = user
    ${adminPath}/file/** = anon
    ${adminPath}/cms/* = anon
    ${adminPath}/cms/site/* = anon
    ${adminPath}/cms/site/select = anon
    ${adminPath}/cms/category/* = anon
    ${adminPath}/cms/category/treeData = anon
    ${adminPath}/cms/article/* = anon
    ${adminPath}/cms/link/* = anon
  defaultFilterChainDefinitions: |  # 默认的授权过滤定义，如果在filterChainDefinitions中已经定义，则该定义会被覆盖。
    /admin/** = anon
    /files/** = anon
    ${adminPath}/login = auth
    ${adminPath}/logout = logout
    ${adminPath}/login-cas = cas
    ${adminPath}/file/** = user
    /druid/** = perms[sys:state:druid]
    ${adminPath}/cms/* = perms[cms:view]
    ${adminPath}/cms/site/* = perms[cms:site:view]
    ${adminPath}/cms/site/select = user
    ${adminPath}/cms/category/* = perms[cms:category:view]
    ${adminPath}/cms/category/treeData = user
    ${adminPath}/cms/article/* = perms[cms:article:view]
    ${adminPath}/cms/link/* = perms[cms:link:view]



#=========================================================#
#=================== Session settings ====================#
#=========================================================#

session:
  sessionTimeout: 1800000  #全局会话超时，单位：毫秒， 20m=1200000ms, 30m=1800000ms, 60m=3600000ms
  mobileSessionTimeout: 43200000  #手机APP设备会话超时参数设置，登录请求参数加 param_deviceType=mobileApp 时有效
  sessionTimeoutClean: 1200000  #定时清理失效会话，清理用户直接关闭浏览器造成的孤立会话
  sessionIdCookieName: style.session.id  #会话唯一标识SessionId在Cookie中的名称。



#=========================================================#
#================= exclude autoconfigure =================#
#=========================================================#

spring:
  autoconfigure:
    exclude:
      org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration,
      org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration,
      org.springframework.boot.autoconfigure.data.web.SpringDataWebAutoConfiguration,

      org.springframework.boot.autoconfigure.web.servlet.HttpEncodingAutoConfiguration,
      org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration,
      org.springframework.boot.autoconfigure.http.codec.CodecsAutoConfiguration,
      org.springframework.boot.autoconfigure.http.HttpMessageConvertersAutoConfiguration,

      org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration,
      org.springframework.boot.autoconfigure.task.TaskSchedulingAutoConfiguration,
      org.springframework.boot.autoconfigure.task.TaskExecutionAutoConfiguration,

      org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,
      org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration,
      org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration,

      org.springframework.boot.autoconfigure.reactor.core.ReactorCoreAutoConfiguration,
      org.springframework.boot.autoconfigure.websocket.servlet.WebSocketServletAutoConfiguration,

      org.springframework.boot.autoconfigure.transaction.jta.JtaAutoConfiguration,
      org.springframework.boot.autoconfigure.transaction.TransactionAutoConfiguration,
      org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,
      org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration,
      org.springframework.boot.autoconfigure.dao.PersistenceExceptionTranslationAutoConfiguration,

      com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration
