#=========================================================#
#=================== Server settings =====================#
#=========================================================#

server:
  port: 9090
  servlet:
    context-path: /
    session:
      cookie:
        http-only: true
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  connection-timeout: 5000ms


#=========================================================#
#=================== Spring settings =====================#
#=========================================================#

spring:
  main:
      bannerMode: "off"
  application:
    name: login-server   # 应用程序名称
  profiles:
    active: dev   # 当前环境名称（注意：不可设置为 test 它是单元测试专用的名称）
  messages:
    encoding: UTF-8
    basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true


#=========================================================#
#================= Mybatis Plus settings =================#
#=========================================================#

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.style.modules.*.entity
  type-aliases-super-type: com.style.web.entity.BaseEntity
  type-enums-package:
  executor-type: reuse
  global-config:
    db-config:
          #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
          id-type: ID_WORKER
          #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
          field-strategy: NOT_NULL
    sql-parser-cache: false
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'


#=========================================================#
#=================== Logging settings ====================#
#=========================================================#
logging:
  config: classpath:configs/log/logback-spring.xml

#eureka:
#  client:
#    register-with-eureka: true #是否将自己注册到eureka服务器中，单机情况无需注册。
#    fetch-registry: true #是否从eureka中获取注册信息。
#    service-url: #eureka客户端与服务端的交互地址。
#      defaultZone: http://localhost:8989/eureka/,http://localhost:9898/eureka/
#  instance:
#    hostname: localhost
#    #ip-address: 127.0.0.1
#    prefer-ip-address: true #是否将自己的IP地址注册到服务器中。
#    instance-id: ${spring.application.name}:${server.port} #自定义实例ID

