server:
  port: ${port}

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: true #是否将自己注册到eureka服务器中，单机情况无需注册。
    fetch-registry: true #是否从eureka中获取注册信息。
    service-url: #eureka客户端与服务端的交互地址。
      defaultZone: http://${eureka.instance.hostname}:${eureka.port}/eureka/
  instance:
    hostname: localhost
    #ip-address: 127.0.0.1
    prefer-ip-address: true #是否将自己的IP地址注册到服务器中。
    instance-id: ${spring.application.name}:${server.port} #自定义实例ID
  server:
    enable-self-preservation: false #Eureka服务端是否开启心跳连接测试
    eviction-interval-timer-in-ms: 60000 #清理间隔（单位毫秒，默认是60*1000）
